services:
  lms:
    image: lms:latest
    build: .
    container_name: lms-app
    ports:
      - "2228:8082"
    networks:
      - lms-network
    restart: unless-stopped
networks:
  lms-network:
    driver: bridge
